//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config"
import reactHooks from "eslint-plugin-react-hooks"

export default [
  {
    // ESLint 9+ only ignores node_modules by default, so everything else that
    // isn't hand-written source has to be listed here. Without this it lints
    // build artifacts and whole duplicate copies of the repo, which is both
    // slow and pure noise — `.output/public` alone produced 101 parse errors,
    // since bundled assets are not in any tsconfig.
    ignores: [
      ".output/**",
      ".wrangler/**",
      ".vinxi/**",
      ".nitro/**",
      // Agent worktrees are full checkouts of this repo; linting them reports
      // every problem two or three extra times.
      ".claude/worktrees/**",
      "packages/*/dist/**",
      // Generated by @tanstack/router-plugin on every build.
      "src/routeTree.gen.ts",
      "graphify-out/**",
      "src/graphify-out/**",
    ],
  },
  ...tanstackConfig,
  {
    // The TanStack config carries no React rules, so the codebase's existing
    // `// eslint-disable-next-line react-hooks/exhaustive-deps` comments were
    // erroring as "rule not found" — suppressing a rule nothing configured.
    //
    // Only the two classic hook rules are enabled. The plugin's own
    // `recommended` preset (v7) also turns on the React Compiler rule set
    // (`set-state-in-effect`, `purity`, `immutability`, …), which is a much
    // larger change in what this codebase is allowed to do than a lint fix
    // should smuggle in.
    files: ["**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "error",
    },
  },
]
