/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout/index'
import { Route as DashboardLayoutPProjectIdIndexRouteImport } from './routes/dashboard/_layout/p/$projectId/index'
import { Route as DashboardLayoutPProjectIdMindmapRouteImport } from './routes/dashboard/_layout/p/$projectId/mindmap'
import { Route as DashboardLayoutPProjectIdRRepoIdRouteImport } from './routes/dashboard/_layout/p/$projectId/r/$repoId'
import { Route as DashboardLayoutPProjectIdNotesNoteIdRouteImport } from './routes/dashboard/_layout/p/$projectId/notes/$noteId'
import { Route as DashboardLayoutPProjectIdMermaidDiagIdRouteImport } from './routes/dashboard/_layout/p/$projectId/mermaid/$diagId'
import { Route as DashboardLayoutPProjectIdRRepoIdIndexRouteImport } from './routes/dashboard/_layout/p/$projectId/r/$repoId/index'
import { Route as DashboardLayoutPProjectIdRRepoIdCCtxIdRouteImport } from './routes/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId'
import { Route as DashboardLayoutPProjectIdRRepoIdCCtxIdIndexRouteImport } from './routes/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId/index'
import { Route as DashboardLayoutPProjectIdRRepoIdCCtxIdFFileIdRouteImport } from './routes/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId/f/$fileId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutPProjectIdIndexRoute =
  DashboardLayoutPProjectIdIndexRouteImport.update({
    id: '/p/$projectId/',
    path: '/p/$projectId/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPProjectIdMindmapRoute =
  DashboardLayoutPProjectIdMindmapRouteImport.update({
    id: '/p/$projectId/mindmap',
    path: '/p/$projectId/mindmap',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPProjectIdRRepoIdRoute =
  DashboardLayoutPProjectIdRRepoIdRouteImport.update({
    id: '/p/$projectId/r/$repoId',
    path: '/p/$projectId/r/$repoId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPProjectIdNotesNoteIdRoute =
  DashboardLayoutPProjectIdNotesNoteIdRouteImport.update({
    id: '/p/$projectId/notes/$noteId',
    path: '/p/$projectId/notes/$noteId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPProjectIdMermaidDiagIdRoute =
  DashboardLayoutPProjectIdMermaidDiagIdRouteImport.update({
    id: '/p/$projectId/mermaid/$diagId',
    path: '/p/$projectId/mermaid/$diagId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPProjectIdRRepoIdIndexRoute =
  DashboardLayoutPProjectIdRRepoIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardLayoutPProjectIdRRepoIdRoute,
  } as any)
const DashboardLayoutPProjectIdRRepoIdCCtxIdRoute =
  DashboardLayoutPProjectIdRRepoIdCCtxIdRouteImport.update({
    id: '/c/$ctxId',
    path: '/c/$ctxId',
    getParentRoute: () => DashboardLayoutPProjectIdRRepoIdRoute,
  } as any)
const DashboardLayoutPProjectIdRRepoIdCCtxIdIndexRoute =
  DashboardLayoutPProjectIdRRepoIdCCtxIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardLayoutPProjectIdRRepoIdCCtxIdRoute,
  } as any)
const DashboardLayoutPProjectIdRRepoIdCCtxIdFFileIdRoute =
  DashboardLayoutPProjectIdRRepoIdCCtxIdFFileIdRouteImport.update({
    id: '/f/$fileId',
    path: '/f/$fileId',
    getParentRoute: () => DashboardLayoutPProjectIdRRepoIdCCtxIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/dashboard/p/$projectId/mindmap': typeof DashboardLayoutPProjectIdMindmapRoute
  '/dashboard/p/$projectId/': typeof DashboardLayoutPProjectIdIndexRoute
  '/dashboard/p/$projectId/mermaid/$diagId': typeof DashboardLayoutPProjectIdMermaidDiagIdRoute
  '/dashboard/p/$projectId/notes/$noteId': typeof DashboardLayoutPProjectIdNotesNoteIdRoute
  '/dashboard/p/$projectId/r/$repoId': typeof DashboardLayoutPProjectIdRRepoIdRouteWithChildren
  '/dashboard/p/$projectId/r/$repoId/': typeof DashboardLayoutPProjectIdRRepoIdIndexRoute
  '/dashboard/p/$projectId/r/$repoId/c/$ctxId': typeof DashboardLayoutPProjectIdRRepoIdCCtxIdRouteWithChildren
  '/dashboard/p/$projectId/r/$repoId/c/$ctxId/': typeof DashboardLayoutPProjectIdRRepoIdCCtxIdIndexRoute
  '/dashboard/p/$projectId/r/$repoId/c/$ctxId/f/$fileId': typeof DashboardLayoutPProjectIdRRepoIdCCtxIdFFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/dashboard/p/$projectId/mindmap': typeof DashboardLayoutPProjectIdMindmapRoute
  '/dashboard/p/$projectId': typeof DashboardLayoutPProjectIdIndexRoute
  '/dashboard/p/$projectId/mermaid/$diagId': typeof DashboardLayoutPProjectIdMermaidDiagIdRoute
  '/dashboard/p/$projectId/notes/$noteId': typeof DashboardLayoutPProjectIdNotesNoteIdRoute
  '/dashboard/p/$projectId/r/$repoId': typeof DashboardLayoutPProjectIdRRepoIdIndexRoute
  '/dashboard/p/$projectId/r/$repoId/c/$ctxId': typeof DashboardLayoutPProjectIdRRepoIdCCtxIdIndexRoute
  '/dashboard/p/$projectId/r/$repoId/c/$ctxId/f/$fileId': typeof DashboardLayoutPProjectIdRRepoIdCCtxIdFFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/dashboard/_layout/p/$projectId/mindmap': typeof DashboardLayoutPProjectIdMindmapRoute
  '/dashboard/_layout/p/$projectId/': typeof DashboardLayoutPProjectIdIndexRoute
  '/dashboard/_layout/p/$projectId/mermaid/$diagId': typeof DashboardLayoutPProjectIdMermaidDiagIdRoute
  '/dashboard/_layout/p/$projectId/notes/$noteId': typeof DashboardLayoutPProjectIdNotesNoteIdRoute
  '/dashboard/_layout/p/$projectId/r/$repoId': typeof DashboardLayoutPProjectIdRRepoIdRouteWithChildren
  '/dashboard/_layout/p/$projectId/r/$repoId/': typeof DashboardLayoutPProjectIdRRepoIdIndexRoute
  '/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId': typeof DashboardLayoutPProjectIdRRepoIdCCtxIdRouteWithChildren
  '/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId/': typeof DashboardLayoutPProjectIdRRepoIdCCtxIdIndexRoute
  '/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId/f/$fileId': typeof DashboardLayoutPProjectIdRRepoIdCCtxIdFFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/p/$projectId/mindmap'
    | '/dashboard/p/$projectId/'
    | '/dashboard/p/$projectId/mermaid/$diagId'
    | '/dashboard/p/$projectId/notes/$noteId'
    | '/dashboard/p/$projectId/r/$repoId'
    | '/dashboard/p/$projectId/r/$repoId/'
    | '/dashboard/p/$projectId/r/$repoId/c/$ctxId'
    | '/dashboard/p/$projectId/r/$repoId/c/$ctxId/'
    | '/dashboard/p/$projectId/r/$repoId/c/$ctxId/f/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/p/$projectId/mindmap'
    | '/dashboard/p/$projectId'
    | '/dashboard/p/$projectId/mermaid/$diagId'
    | '/dashboard/p/$projectId/notes/$noteId'
    | '/dashboard/p/$projectId/r/$repoId'
    | '/dashboard/p/$projectId/r/$repoId/c/$ctxId'
    | '/dashboard/p/$projectId/r/$repoId/c/$ctxId/f/$fileId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/_layout'
    | '/dashboard/_layout/'
    | '/dashboard/_layout/p/$projectId/mindmap'
    | '/dashboard/_layout/p/$projectId/'
    | '/dashboard/_layout/p/$projectId/mermaid/$diagId'
    | '/dashboard/_layout/p/$projectId/notes/$noteId'
    | '/dashboard/_layout/p/$projectId/r/$repoId'
    | '/dashboard/_layout/p/$projectId/r/$repoId/'
    | '/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId'
    | '/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId/'
    | '/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId/f/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/p/$projectId/': {
      id: '/dashboard/_layout/p/$projectId/'
      path: '/p/$projectId'
      fullPath: '/dashboard/p/$projectId/'
      preLoaderRoute: typeof DashboardLayoutPProjectIdIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/p/$projectId/mindmap': {
      id: '/dashboard/_layout/p/$projectId/mindmap'
      path: '/p/$projectId/mindmap'
      fullPath: '/dashboard/p/$projectId/mindmap'
      preLoaderRoute: typeof DashboardLayoutPProjectIdMindmapRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/p/$projectId/r/$repoId': {
      id: '/dashboard/_layout/p/$projectId/r/$repoId'
      path: '/p/$projectId/r/$repoId'
      fullPath: '/dashboard/p/$projectId/r/$repoId'
      preLoaderRoute: typeof DashboardLayoutPProjectIdRRepoIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/p/$projectId/notes/$noteId': {
      id: '/dashboard/_layout/p/$projectId/notes/$noteId'
      path: '/p/$projectId/notes/$noteId'
      fullPath: '/dashboard/p/$projectId/notes/$noteId'
      preLoaderRoute: typeof DashboardLayoutPProjectIdNotesNoteIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/p/$projectId/mermaid/$diagId': {
      id: '/dashboard/_layout/p/$projectId/mermaid/$diagId'
      path: '/p/$projectId/mermaid/$diagId'
      fullPath: '/dashboard/p/$projectId/mermaid/$diagId'
      preLoaderRoute: typeof DashboardLayoutPProjectIdMermaidDiagIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/p/$projectId/r/$repoId/': {
      id: '/dashboard/_layout/p/$projectId/r/$repoId/'
      path: '/'
      fullPath: '/dashboard/p/$projectId/r/$repoId/'
      preLoaderRoute: typeof DashboardLayoutPProjectIdRRepoIdIndexRouteImport
      parentRoute: typeof DashboardLayoutPProjectIdRRepoIdRoute
    }
    '/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId': {
      id: '/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId'
      path: '/c/$ctxId'
      fullPath: '/dashboard/p/$projectId/r/$repoId/c/$ctxId'
      preLoaderRoute: typeof DashboardLayoutPProjectIdRRepoIdCCtxIdRouteImport
      parentRoute: typeof DashboardLayoutPProjectIdRRepoIdRoute
    }
    '/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId/': {
      id: '/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId/'
      path: '/'
      fullPath: '/dashboard/p/$projectId/r/$repoId/c/$ctxId/'
      preLoaderRoute: typeof DashboardLayoutPProjectIdRRepoIdCCtxIdIndexRouteImport
      parentRoute: typeof DashboardLayoutPProjectIdRRepoIdCCtxIdRoute
    }
    '/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId/f/$fileId': {
      id: '/dashboard/_layout/p/$projectId/r/$repoId/c/$ctxId/f/$fileId'
      path: '/f/$fileId'
      fullPath: '/dashboard/p/$projectId/r/$repoId/c/$ctxId/f/$fileId'
      preLoaderRoute: typeof DashboardLayoutPProjectIdRRepoIdCCtxIdFFileIdRouteImport
      parentRoute: typeof DashboardLayoutPProjectIdRRepoIdCCtxIdRoute
    }
  }
}

interface DashboardLayoutPProjectIdRRepoIdCCtxIdRouteChildren {
  DashboardLayoutPProjectIdRRepoIdCCtxIdIndexRoute: typeof DashboardLayoutPProjectIdRRepoIdCCtxIdIndexRoute
  DashboardLayoutPProjectIdRRepoIdCCtxIdFFileIdRoute: typeof DashboardLayoutPProjectIdRRepoIdCCtxIdFFileIdRoute
}

const DashboardLayoutPProjectIdRRepoIdCCtxIdRouteChildren: DashboardLayoutPProjectIdRRepoIdCCtxIdRouteChildren =
  {
    DashboardLayoutPProjectIdRRepoIdCCtxIdIndexRoute:
      DashboardLayoutPProjectIdRRepoIdCCtxIdIndexRoute,
    DashboardLayoutPProjectIdRRepoIdCCtxIdFFileIdRoute:
      DashboardLayoutPProjectIdRRepoIdCCtxIdFFileIdRoute,
  }

const DashboardLayoutPProjectIdRRepoIdCCtxIdRouteWithChildren =
  DashboardLayoutPProjectIdRRepoIdCCtxIdRoute._addFileChildren(
    DashboardLayoutPProjectIdRRepoIdCCtxIdRouteChildren,
  )

interface DashboardLayoutPProjectIdRRepoIdRouteChildren {
  DashboardLayoutPProjectIdRRepoIdIndexRoute: typeof DashboardLayoutPProjectIdRRepoIdIndexRoute
  DashboardLayoutPProjectIdRRepoIdCCtxIdRoute: typeof DashboardLayoutPProjectIdRRepoIdCCtxIdRouteWithChildren
}

const DashboardLayoutPProjectIdRRepoIdRouteChildren: DashboardLayoutPProjectIdRRepoIdRouteChildren =
  {
    DashboardLayoutPProjectIdRRepoIdIndexRoute:
      DashboardLayoutPProjectIdRRepoIdIndexRoute,
    DashboardLayoutPProjectIdRRepoIdCCtxIdRoute:
      DashboardLayoutPProjectIdRRepoIdCCtxIdRouteWithChildren,
  }

const DashboardLayoutPProjectIdRRepoIdRouteWithChildren =
  DashboardLayoutPProjectIdRRepoIdRoute._addFileChildren(
    DashboardLayoutPProjectIdRRepoIdRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
  DashboardLayoutPProjectIdMindmapRoute: typeof DashboardLayoutPProjectIdMindmapRoute
  DashboardLayoutPProjectIdIndexRoute: typeof DashboardLayoutPProjectIdIndexRoute
  DashboardLayoutPProjectIdMermaidDiagIdRoute: typeof DashboardLayoutPProjectIdMermaidDiagIdRoute
  DashboardLayoutPProjectIdNotesNoteIdRoute: typeof DashboardLayoutPProjectIdNotesNoteIdRoute
  DashboardLayoutPProjectIdRRepoIdRoute: typeof DashboardLayoutPProjectIdRRepoIdRouteWithChildren
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
  DashboardLayoutPProjectIdMindmapRoute: DashboardLayoutPProjectIdMindmapRoute,
  DashboardLayoutPProjectIdIndexRoute: DashboardLayoutPProjectIdIndexRoute,
  DashboardLayoutPProjectIdMermaidDiagIdRoute:
    DashboardLayoutPProjectIdMermaidDiagIdRoute,
  DashboardLayoutPProjectIdNotesNoteIdRoute:
    DashboardLayoutPProjectIdNotesNoteIdRoute,
  DashboardLayoutPProjectIdRRepoIdRoute:
    DashboardLayoutPProjectIdRRepoIdRouteWithChildren,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
