/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout/index'
import { Route as DashboardPProjectIdIndexRouteImport } from './routes/dashboard/p/$projectId/index'
import { Route as DashboardPProjectIdRRepoIdRouteImport } from './routes/dashboard/p/$projectId/r/$repoId'
import { Route as DashboardPProjectIdRRepoIdCCtxIdRouteImport } from './routes/dashboard/p/$projectId/r/$repoId/c/$ctxId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardPProjectIdIndexRoute =
  DashboardPProjectIdIndexRouteImport.update({
    id: '/dashboard/p/$projectId/',
    path: '/dashboard/p/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardPProjectIdRRepoIdRoute =
  DashboardPProjectIdRRepoIdRouteImport.update({
    id: '/dashboard/p/$projectId/r/$repoId',
    path: '/dashboard/p/$projectId/r/$repoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardPProjectIdRRepoIdCCtxIdRoute =
  DashboardPProjectIdRRepoIdCCtxIdRouteImport.update({
    id: '/c/$ctxId',
    path: '/c/$ctxId',
    getParentRoute: () => DashboardPProjectIdRRepoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/dashboard/p/$projectId/': typeof DashboardPProjectIdIndexRoute
  '/dashboard/p/$projectId/r/$repoId': typeof DashboardPProjectIdRRepoIdRouteWithChildren
  '/dashboard/p/$projectId/r/$repoId/c/$ctxId': typeof DashboardPProjectIdRRepoIdCCtxIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/dashboard/p/$projectId': typeof DashboardPProjectIdIndexRoute
  '/dashboard/p/$projectId/r/$repoId': typeof DashboardPProjectIdRRepoIdRouteWithChildren
  '/dashboard/p/$projectId/r/$repoId/c/$ctxId': typeof DashboardPProjectIdRRepoIdCCtxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/dashboard/p/$projectId/': typeof DashboardPProjectIdIndexRoute
  '/dashboard/p/$projectId/r/$repoId': typeof DashboardPProjectIdRRepoIdRouteWithChildren
  '/dashboard/p/$projectId/r/$repoId/c/$ctxId': typeof DashboardPProjectIdRRepoIdCCtxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/p/$projectId/'
    | '/dashboard/p/$projectId/r/$repoId'
    | '/dashboard/p/$projectId/r/$repoId/c/$ctxId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/p/$projectId'
    | '/dashboard/p/$projectId/r/$repoId'
    | '/dashboard/p/$projectId/r/$repoId/c/$ctxId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/_layout'
    | '/dashboard/_layout/'
    | '/dashboard/p/$projectId/'
    | '/dashboard/p/$projectId/r/$repoId'
    | '/dashboard/p/$projectId/r/$repoId/c/$ctxId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  DashboardPProjectIdIndexRoute: typeof DashboardPProjectIdIndexRoute
  DashboardPProjectIdRRepoIdRoute: typeof DashboardPProjectIdRRepoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/p/$projectId/': {
      id: '/dashboard/p/$projectId/'
      path: '/dashboard/p/$projectId'
      fullPath: '/dashboard/p/$projectId/'
      preLoaderRoute: typeof DashboardPProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/p/$projectId/r/$repoId': {
      id: '/dashboard/p/$projectId/r/$repoId'
      path: '/dashboard/p/$projectId/r/$repoId'
      fullPath: '/dashboard/p/$projectId/r/$repoId'
      preLoaderRoute: typeof DashboardPProjectIdRRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/p/$projectId/r/$repoId/c/$ctxId': {
      id: '/dashboard/p/$projectId/r/$repoId/c/$ctxId'
      path: '/c/$ctxId'
      fullPath: '/dashboard/p/$projectId/r/$repoId/c/$ctxId'
      preLoaderRoute: typeof DashboardPProjectIdRRepoIdCCtxIdRouteImport
      parentRoute: typeof DashboardPProjectIdRRepoIdRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface DashboardPProjectIdRRepoIdRouteChildren {
  DashboardPProjectIdRRepoIdCCtxIdRoute: typeof DashboardPProjectIdRRepoIdCCtxIdRoute
}

const DashboardPProjectIdRRepoIdRouteChildren: DashboardPProjectIdRRepoIdRouteChildren =
  {
    DashboardPProjectIdRRepoIdCCtxIdRoute:
      DashboardPProjectIdRRepoIdCCtxIdRoute,
  }

const DashboardPProjectIdRRepoIdRouteWithChildren =
  DashboardPProjectIdRRepoIdRoute._addFileChildren(
    DashboardPProjectIdRRepoIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  DashboardPProjectIdIndexRoute: DashboardPProjectIdIndexRoute,
  DashboardPProjectIdRRepoIdRoute: DashboardPProjectIdRRepoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
